# Generated by Django 4.2.5 on 2024-01-17 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='toliq ism')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
        ),
        migrations.CreateModel(
            name='Our_advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartibi')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='universities/')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='univesitet nomi')),
                ('province', models.CharField(max_length=100)),
                ('video', models.URLField(blank=True, null=True)),
                ('gallery', models.ManyToManyField(to='app.universityimage', verbose_name='rasmlar')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='toliq ism')),
                ('image', models.ImageField(upload_to='images/')),
                ('faculty', models.CharField(max_length=100, verbose_name='qaysi yonalish')),
                ('opinion', models.TextField(verbose_name='Konsalting haqidagi fikri')),
                ('student_info', models.CharField(max_length=100)),
                ('video', models.URLField(blank=True, null=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.university')),
            ],
        ),
    ]
