# Generated by Django 4.2.9 on 2024-01-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_advantages',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
