# Generated by Django 4.2.9 on 2024-01-27 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_our_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='message',
        ),
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='oquv_darajasi',
            field=models.CharField(choices=[('1', 'Bakalavr'), ('2', 'Magistr'), ('3', 'Doktorantura')], default='new', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='phone_number',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\+998\\d{9}$')]),
        ),
    ]
