# Generated by Django 4.2.9 on 2024-01-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_form_message_form_email_form_oquv_darajasi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='full_name',
        ),
        migrations.AddField(
            model_name='form',
            name='first_name',
            field=models.CharField(default='new', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='last_name',
            field=models.CharField(default='manual', max_length=50),
            preserve_default=False,
        ),
    ]
