# Generated by Django 4.2.9 on 2024-01-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_form_full_name_form_first_name_form_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='email',
        ),
        migrations.AddField(
            model_name='form',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
